# Generated by Django 5.2.9 on 2025-12-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(default='맛있는 치킨집', max_length=100)),
                ('status', models.CharField(choices=[('pending_payment', '결제 대기'), ('pending_acceptance', '주문 접수 대기'), ('preparing', '조리중'), ('cancelled', '주문 취소')], default='pending_payment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
